### PR TITLE
Fix for wdtStart flag

### LINKED ISSUE #19: wdtStarted never set to false
`wdtStarted` is set to true in `TheThingsNode::WDT_start()`, but in `TheThingsNode::WDT_stop()`, not set to false.

https://github.com/TheThingsNetwork/arduino-node-lib/blob/124b4821e648816e94089df8da082276e9f7e887/src/TheThingsNode.cpp#L874-L889

### PR DESCRIPTION
**Pull request by pedzed**
Closes #19

### CODE REVIEW

**Comment by jpmeijers** [comment]
The suggestion that this is a bug makes sense. I however find it strange that no one else complained about this. Let's at least test this before merging in.

**Comment by johanstokking** [comment]
I'm quite sure this is a valid bug.

@pedzed did you test this with going on/off/on/off?

**Comment by loganmc10** [comment]
Is there something I can do to help test this? It seems like a pretty obvious typo

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
Released in https://github.com/TheThingsNetwork/arduino-node-lib/releases/tag/v2.0.8

**Pull request merged**
